// <auto-generated />
using System;
using EFCore.DataClassification.Models;
using EFCore.DataClassification.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.DataClassification.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215124752_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adminkey")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Admin Sleutel")
                        .HasAnnotation("DataClassification:Label", "Highly Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Naam")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Bike Brand")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<int>("GearCount")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Bike Owner")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car model")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<int>("UniqueId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Unique Car Identifier")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "car relase year")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Mailing Address")
                        .HasAnnotation("DataClassification:Label", "Address")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Email Address")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Author")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Body")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublisherUnikeUnitID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Publisher Unique Unit ID")
                        .HasAnnotation("DataClassification:Label", "Very Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("DataClassification:InformationType", "Release Date")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Owner Name")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Home Size")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Admin Reference")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Phone Number")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Salary")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Financial Information")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.User", null)
                        .WithMany("Games")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.Admin", "Admin")
                        .WithMany("Users")
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
