// <auto-generated />
using EFCore.DataClassification.Models;
using EFCore.DataClassification.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.DataClassification.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124195537_adresschangev2")]
    partial class adresschangev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adminkey")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Security Info")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Contact Info")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "huis adress")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Contact Info")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Phone Number")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Salary")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Salary blabla")
                        .HasAnnotation("DataClassification:Label", "blablabla")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
