// <auto-generated />
using System;
using EFCore.DataClassification.Models;
using EFCore.DataClassification.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.DataClassification.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105230122_SmokeTest_Comprehensive_AllEdgeCases")]
    partial class SmokeTest_Comprehensive_AllEdgeCases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Email")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("FavoriteBookAuthor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Favorite Author")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin First Name")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("InscriptionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Inscription Number")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Last Name")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Notes")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Phone Number")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GearCount")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Bike Serial Number")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car Model Name")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car Notes")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car Owner Email")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car Owner Name")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("UniqueId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Unique Car Identifier")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("VehicleIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Vehicle Identification Number")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car Manufacturing Year")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Mailing Address")
                        .HasAnnotation("DataClassification:Label", "Address")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Email Address")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Customer Full Name")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Phone Number")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Body")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Summary")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Title")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Writer Name")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Game Description")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Developer Name")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Game Genre")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("DataClassification:InformationType", "Game Price")
                        .HasAnnotation("DataClassification:Label", "Financial")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("PublisherID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Publisher ID")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Location")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Owner Name")
                        .HasAnnotation("DataClassification:Label", "Personal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("DataClassification:InformationType", "Home Price")
                        .HasAnnotation("DataClassification:Label", "Financial")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Home Size")
                        .HasAnnotation("DataClassification:Label", "Property")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Admin Reference")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Private")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Email Address")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "User Full Name")
                        .HasAnnotation("DataClassification:Label", "Personal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Phone Number")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("DataClassification:InformationType", "Financial Information")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Critical);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "User Status")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.User", null)
                        .WithMany("Games")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.Admin", "Admin")
                        .WithMany("Users")
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
