// <auto-generated />
using System;
using EFCore.DataClassification.Models;
using EFCore.DataClassification.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.DataClassification.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117215625_SmokeTest_ClassificationOnly")]
    partial class SmokeTest_ClassificationOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adminkey")
                        .HasColumnType("int")
                        .HasColumnName("AdminKeyCode")
                        .HasAnnotation("DataClassification:InformationType", "Admin Key")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Admin Email")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GearCount")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Bike Gear Count")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Bike Serial")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Car model")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<int>("UniqueId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Unique Car Identifier")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Vehicle Identification Number")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Car manufacturing year")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Mailing Address")
                        .HasAnnotation("DataClassification:Label", "Address")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Email Address")
                        .HasAnnotation("DataClassification:Label", "Contact")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Body")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reviewer")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Reviewer")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Title")
                        .HasAnnotation("DataClassification:Label", "Docs")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Game Description")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Game Genre")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublisherUnikeUnitID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Publisher Unique Unit ID")
                        .HasAnnotation("DataClassification:Label", "Very Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("DataClassification:InformationType", "Release Date")
                        .HasAnnotation("DataClassification:Label", "Intern")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Game Title")
                        .HasAnnotation("DataClassification:Label", "Public")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.None);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Location")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.PersonBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Full Name")
                        .HasAnnotation("DataClassification:Label", "Personal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Admin Reference")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address")
                        .HasAnnotation("DataClassification:InformationType", "Home Address")
                        .HasAnnotation("DataClassification:Label", "Location")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "User Email")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<DateTime?>("LastPasswordChangeUtc")
                        .HasColumnType("datetime2")
                        .HasAnnotation("DataClassification:InformationType", "Last Password Change")
                        .HasAnnotation("DataClassification:Label", "Security")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Phone Number")
                        .HasAnnotation("DataClassification:Label", "Internal")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.Property<int?>("Salary")
                        .HasColumnType("int")
                        .HasAnnotation("DataClassification:InformationType", "Financial Information")
                        .HasAnnotation("DataClassification:Label", "Confidential")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.Property<string>("ShadowSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Shadow Secret")
                        .HasAnnotation("DataClassification:Label", "Security")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Contractor", b =>
                {
                    b.HasBaseType("EFCore.DataClassification.WebApi.Models.PersonBase");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Agency Name")
                        .HasAnnotation("DataClassification:Label", "Employment")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Employee", b =>
                {
                    b.HasBaseType("EFCore.DataClassification.WebApi.Models.PersonBase");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("DataClassification:InformationType", "Employee Code")
                        .HasAnnotation("DataClassification:Label", "Employment")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.Low);

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("DataClassification:InformationType", "Salary")
                        .HasAnnotation("DataClassification:Label", "Financial")
                        .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Game", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.User", null)
                        .WithMany("Games")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.PersonBase", b =>
                {
                    b.OwnsOne("EFCore.DataClassification.WebApi.Models.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<int>("PersonBaseId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactEmail")
                                .HasAnnotation("DataClassification:InformationType", "Email Address")
                                .HasAnnotation("DataClassification:Label", "Contact")
                                .HasAnnotation("DataClassification:Rank", SensitivityRank.High);

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactPhone")
                                .HasAnnotation("DataClassification:InformationType", "Phone Number")
                                .HasAnnotation("DataClassification:Label", "Contact")
                                .HasAnnotation("DataClassification:Rank", SensitivityRank.Medium);

                            b1.HasKey("PersonBaseId");

                            b1.ToTable("People");

                            b1.WithOwner()
                                .HasForeignKey("PersonBaseId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.Admin", "Admin")
                        .WithMany("Users")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Contractor", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.PersonBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.DataClassification.WebApi.Models.Contractor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Employee", b =>
                {
                    b.HasOne("EFCore.DataClassification.WebApi.Models.PersonBase", null)
                        .WithOne()
                        .HasForeignKey("EFCore.DataClassification.WebApi.Models.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.Admin", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFCore.DataClassification.WebApi.Models.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
